name: flake8-test


on: [push, pull_request]


jobs:
  flake8-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: poetry-install
        run: |
          pip install poetry
          poetry install
      - name: linter-test
        run: |
          poetry run flake8 hexlet_pytest