name: tests


on: [push, pull_request]


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: poetry-install
        run: |
          pip install poetry
          poetry install
      - name: check-tests
        run: poetry run pytest